# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mordante's blog
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  About C++ projects I work on.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://mordante.github.io"
github_username:  mordante

tag_page: '/tags/'

permalink: /:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
#kramdown:
#  highlighter: rouge
#  default_lang: c++
#  syntax_highlighter_opts:
#    block:
#      line_numbers: true


theme: jekyll-theme-merlot

exclude: [vendor]

plugins:
  - jekyll-theme-minimal
  - jekyll-theme-merlot
