# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mordante's blog
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Mainly about coding projects I work on.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://mordante.github.io"
#twitter_username: jekyllrb
github_username:  mordante

# Build settings
markdown: kramdown

theme: jekyll-theme-merlot

exclude: [vendor]

plugins:
  - jekyll-theme-minimal
  - jekyll-theme-merlot
  - jekyll-theme-dinky
